language: node_js
node_js: --lts
before_script:
  - git config user.name "jawn-ha"
  - git config user.email "zhanghuiun125@qq.com"
  - sed -i'' 
"s~https://github.com/jawn-ha/jawn-ha.github.io.git~https://${GITHUB_ACCESS_TOKEN}@github.com/<yourname>/<reopname>.git~" _config.yml
script:
  - hexo g
  - hexo d
