# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "jawn-ha"
  - git config user.email "zhanghuijun125@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-resource
env:
 global:
   - GH_REF: github.com/jawn-ha/jawn-ha.github.io.git
