# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 7.9.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - hexo 

before_install:
  - git config user.name jawn-ha
  - git config user.email zhanghuijun125@qq.com
  - sed -i'' "s~https://github.com/jawn-ha/jawn-ha.github.io.git~https://${Travis_Token}@github.com/jawn-ha/jawn-ha.github.io.git~" _config.yml

# Start: Build Lifecycle
install:
  - npm install -g hexo-cli
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - npm run deploy
# End: Build LifeCycle

